DOMAIN = "storesnearby"

"""Google Places API configuration."""
BASE_API_URL = "https://maps.googleapis.com/maps/api/place/details/json"
API_KEY = "<your_api_key>"

"""Attributes used in entity."""
ATTR_NAME = "name"
ATTR_COMMERCIAL_NAME = "commercial_name"
ATTR_PLACEID = "place_id"
ATTR_OPENING_HOURS_0 = "opening_hours_monday"
ATTR_OPENING_HOURS_1 = "opening_hours_tuesday"
ATTR_OPENING_HOURS_2 = "opening_hours_wednesday"
ATTR_OPENING_HOURS_3 = "opening_hours_thursday"
ATTR_OPENING_HOURS_4 = "opening_hours_friday"
ATTR_OPENING_HOURS_5 = "opening_hours_saturday"
ATTR_OPENING_HOURS_6 = "opening_hours_sunday"
ATTR_LAST_FORCED_UPDATE = "last_forced_update"
ATTR_OPEN_NOW = "open_now"

"""Properties used in API response"""
API_RESULT = "result"
API_NAME = "name"
API_OPENING_HOURS = "opening_hours"
API_WEEKDAY_TEXT = "weekday_text"
API_OPEN_NOW = "open_now"

"""Properties used in configuration.yaml."""
CONF_STORES = "stores"
CONF_NAME = "name"
CONF_PLACEID = "place_id"